analyzer:
  errors:
    library_private_types_in_public_api: ignore
    unnecessary_getters_setters: ignore
    use_late_for_private_fields_and_variables: ignore
  exclude: 
    - lib/l10n/
    - lib/**/*.g.dart
include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false