name: popcart
description: Popcart Africa
version: 1.0.0+2
publish_to: none

environment:
  sdk: ^3.5.3

dependencies:
#  agora_rtc_engine: ^6.5.0
  bloc: ^8.1.4
  dio: ^5.7.0
  envied: ^1.1.1
  equatable: ^2.0.7
  extended_image: ^9.1.0
  file_picker: ^8.1.4
  firebase_analytics: ^11.3.5
  firebase_core: ^3.8.0
  firebase_crashlytics: ^4.1.5
  firebase_messaging: ^15.1.5
  firebase_performance_dio: ^0.7.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^8.1.6
  flutter_gen: ^5.8.0
  flutter_hooks: ^0.20.5
  flutter_image_compress: ^2.3.0
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  form_validator: ^2.1.1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  go_router: ^14.6.1
  go_router_paths: ^0.2.2
  haptic_feedback: ^0.5.1+1
  infinite_scroll_pagination: ^4.1.0
  intl: ^0.19.0
  keyboard_attachable: ^2.2.0
  mime: ^2.0.0
  path_provider: ^2.1.5
  pdf_compressor: ^0.2.0
  permission_handler: ^11.3.1
  pinput: ^5.0.0
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.3.3
  skeletonizer: ^1.4.3
  timer_count_down: ^2.2.2
  toastification: ^2.3.0
  webview_flutter: ^4.10.0
  lottie: ^3.2.0
  video_player: ^2.9.5

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  envied_generator: ^1.1.1
  flutter_gen_runner: ^5.8.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/animations/
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/WorkSans-VariableFont_wght.ttf

flutter_gen:
  output: lib/gen/
  
  integrations:
    flutter_svg: true

  assets:
    enabled: true
    outputs:
      class_name: AppAssets



targets:
  $default:
    builders:
      flutter_gen_runner:
        enabled: true
        options:
          flutter_svg: true

flutter_native_splash:
  background_image: "assets/images/splash_image.png"
  android_12:
    color: "#111214"
    # icon_background_color: "#111214"