name: popcart
description: Popcart Africa
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.4
  dio: ^5.7.0
  envied: ^1.0.0
  firebase_analytics: ^11.3.5
  firebase_core: ^3.8.0
  firebase_crashlytics: ^4.1.5
  firebase_messaging: ^15.1.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_gen: ^5.8.0
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.2
  go_router: ^14.6.1
  go_router_paths: ^0.2.2
  intl: ^0.19.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.3
  toastification: ^2.3.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  envied_generator: ^1.0.0
  flutter_gen_runner: ^5.8.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/WorkSans-VariableFont_wght.ttf

flutter_gen:
  output: lib/gen/
  
  integrations:
    flutter_svg: true

  assets:
    enabled: true
    outputs:
      class_name: AppAssets

  style:
    filename: snake_case


targets:
  $default:
    builders:
      flutter_gen_runner:
        enabled: true
        options:
          flutter_svg: true

flutter_native_splash:
  background_image: "assets/images/splash_image.png"
  android_12:
    color: "#111214"
    # icon_background_color: "#111214"