# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
ruby '3.4.2' # Match your Ruby version
gem "fastlane", ">= 2.227.0"
gem "abbrev"
gem "logger"
