name: iOS Build and Deploy to TestFlight

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.29.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Setup keychain
        run: |
          security create-keychain -p ${{ secrets.KEYCHAIN_PASSWORD }} ci-keychain
          security default-keychain -s ci-keychain
          security unlock-keychain -p ${{ secrets.KEYCHAIN_PASSWORD }} ci-keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k ${{ secrets.KEYCHAIN_PASSWORD }} ci-keychain
          echo "${{ secrets.CERTIFICATE_BASE64 }}" | base64 --decode > certificate.p12
          security import certificate.p12 -k ci-keychain -P ${{ secrets.CERTIFICATE_PASSWORD }} -T /usr/bin/codesign
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "${{ secrets.PROVISIONING_PROFILE_BASE64 }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/popcart_adhoc_distro.mobileprovision

      - name: Build iOS
        run: |
          flutter build ios --release --flavor=production --target=lib/app/main.prod.dart --verbose
          cd ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -archivePath build/Runner.xcarchive archive \
            CODE_SIGN_STYLE="Automatic" \
            CODE_SIGN_IDENTITY="iOS Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="popcart_adhoc_distro" \
            DEVELOPMENT_TEAM="${{ secrets.DEVELOPMENT_TEAM }}"
          xcodebuild -exportArchive -archivePath build/Runner.xcarchive -exportPath build/ipa -exportOptionsPlist ExportOptions.plist

      - name: Install Fastlane
        run: |
          cd ios
          bundle install

      - name: Deploy to TestFlight
        env:
          APP_STORE_API_KEY_ID: ${{ secrets.APP_STORE_API_KEY_ID }}
          APP_STORE_API_ISSUER_ID: ${{ secrets.APP_STORE_API_ISSUER_ID }}
          APP_STORE_API_KEY: ${{ secrets.APP_STORE_API_KEY }}
        run: |
          cd ios
          fastlane deliver --ipa "../build/ipa/Runner.ipa" --api_key_path "fastlane/api_key.json" --skip_metadata true --skip_screenshots true
